apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflowTemplate
metadata:
  name: evaluate-template
  namespace: {{ include "testbench.namespace" . }}
  labels:
    {{- include "testbench.labels" . | nindent 4 }}
    {{- include "testbench.workflowLabels" . | nindent 4 }}
spec:
  # Configuration parameters that can be overridden
  config:
    openApiBasePath:
      type: string
      description: "Base path for OpenAI API"
      default: "http://ai-gateway-litellm.ai-gateway:4000"

  # Steps to execute
  steps:
    - name: evaluate-results
      artifacts:
        paths:
          - "data/experiments/evaluated_experiment.json"
      run:
        image: {{ include "testbench.image" . }}
        args:
          - evaluate.py
        env:
          - name: OPENAI_BASE_URL
            value: "{{`{{ config.openApiBasePath }}`}}"
