apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: example-workflow
  namespace: testkube
  labels:
    testkube.io/test-category: ragas-evaluation
    app: testworkflows

spec:
  content:
    files:
      - path: /data/datasets/experiment.json
        contentFrom:
          configMapKeyRef:
            name: experiment
            key: experiment.json

  container:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        valueFrom:
          configMapKeyRef:
            name: otel-config
            key: OTEL_EXPORTER_OTLP_ENDPOINT

  use:
  - name: run-template
    config:
      agentUrl: "http://weather-agent.sample-agents:8000"
  - name: evaluate-template
    config:
      openApiBasePath: "http://ai-gateway-litellm.ai-gateway:4000"
  - name: publish-template
  - name: visualize-template