apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lgtm/
  - otel-config.yaml
  - otel-config-agent.yaml
  - weather-agent.yaml
  - experiment.yaml
  - example-workflow.yaml
  - example-workflow-trigger.yaml
