apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lgtm/
  - agent-gateway.yaml
  - ai-gateway.yaml
  - agent-runtime-config.yaml
  - otel-config.yaml
  - weather-agent.yaml
  - tool-gateway.yaml
  - weather-mcp-server.yaml
  - example-experiment.yaml
