kind: Namespace
apiVersion: v1
metadata:
  name: sample-agents
---
apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: Agent
metadata:
  labels:
    app.kubernetes.io/name: agent-runtime-operator
    app.kubernetes.io/managed-by: kustomize
  name: weather-agent
  namespace: sample-agents
spec:
  description: "Agent to answer questions about the time and weather in a city."
  instruction: |-
    You are a helpful agent who can answer user questions about the time and weather in a city.
  model: "gemini/gemini-2.5-flash"
  aiGatewayRef:
    name: ai-gateway
    namespace: ai-gateway
  tools:
    - name: weather-mcp-server
      upstream:
        toolRouteRef:
          name: weather-mcp-server
  protocols:
    - type: A2A
      name: a2a-8000
  exposed: true
  env:
    - name: OTEL_SERVICE_NAME
      value: "weather-agent"
  envFrom:
    - configMapRef:
        name: otel-config
        optional: true
