apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflowTemplate
metadata:
  name: publish-template
  namespace: testkube
  labels:
    app.kubernetes.io/name: testbench
    app.kubernetes.io/version: "0.0.1"
    testkube.io/test-category: ragas-evaluation
    app: testworkflows
spec:
  config:
    experimentName:
      type: string
      description: "Name of the experiment for metric labeling"
  steps:
    - name: publish-metrics
      run:
        image: ghcr.io/agentic-layer/testbench/testworkflows:0.0.1
        args:
          - publish.py
          - "{{ config.experimentName }}"
          - "{{ execution.id }}"
          - "{{ execution.number }}"
