---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - runtime.agentic-layer.ai
  resources:
  - aigateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testbench.agentic-layer.ai
  resources:
  - experiments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testbench.agentic-layer.ai
  resources:
  - experiments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tests.testkube.io
  resources:
  - testtriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testworkflows.testkube.io
  resources:
  - testworkflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
